apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: airquality-kube-cron-job
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: kube-cron-job
            image: airquality:latest
            args: ["100"]